name: CI

on: pull_request

jobs:
  Continuous_Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8

      - name: Instalar o Poetry via pip
        run: pip install poetry

      - name: Instalar  dependencias com o Poetry
        run: poetry install

      - name: Rodar minha rotina de testes com o Poetry
        run: pytest -v test\teste.py